-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 00:08:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spring_book_test
-- -----------------------------------------------------
-- Spring book 项目测试数据库
DROP SCHEMA IF EXISTS `spring_book_test` ;

-- -----------------------------------------------------
-- Schema spring_book_test
--
-- Spring book 项目测试数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_book_test` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `spring_book_test` ;

-- -----------------------------------------------------
-- Table `spring_book_test`.`tab_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring_book_test`.`tab_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `spring_book_test`.`tab_user` (
  `id` BIGINT(8) UNSIGNED NOT NULL COMMENT 'Id',
  `name` VARCHAR(45) NULL COMMENT '用户名称',
  `user_code` VARCHAR(45) NULL COMMENT '用户编码',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT(1) NOT NULL COMMENT '伪删除标识字段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
